Features/homepage
karvel-code/NewYorkTimes-Article- pull request #1
Opened 2021-01-13 14:22 UTC by karvel-code

2021-01-13 16:01 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @karvel-code and @nganifaith. Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The PR message should be descriptive and meaningful, please *edit* the actual. Recommendations give a brief summary of the things you have done, the features, and/or the goals of the project
- [ ] Social media icons out of place
![image](https://user-images.githubusercontent.com/25774518/104475537-d60aad00-5584-11eb-885c-30ea78eb51a1.png)
- [ ] Image broken and both image and articles should be links
![image](https://user-images.githubusercontent.com/25774518/104475721-0b16ff80-5585-11eb-984e-b7aa00641bf7.png)

- [ ] Images should have the with of the paragraph, and the paragraphs should be all aligned
![image](https://user-images.githubusercontent.com/25774518/104476094-76f96800-5585-11eb-9de0-3ea67666a166.png)

- [ ] Images and article titles should be links, the sections don't look like the original design, the images should be horizontally aligned.
![image](https://user-images.githubusercontent.com/25774518/104476664-1a4a7d00-5586-11eb-9ddf-1fcd9dd891dd.png)


### [OPTIONAL]  :yellow_circle:  

- [ ] The readme has most of the relevant information and that's great!, but it is difficult to read in the *Getting started* section, it contains a number of steps but the way is presented makes it hard to follow. To fix this instead of having a paragraph with all the information please put each step in a new line, so is visually more appealing and readable.
- [ ] The Author section has some markdown syntax issues, and change the keyword `githubhandle` for your actual github account name. example:
  *BAD*
  Julio: [@githubhandle] (https://www.github.com/jubaan) // this has a space between `]` and `(`
  Julio: [@githubhandle](https://www.github.com/jubaan) // this uses a generic username

  *GREAT*
  Julio: [@jubaan](https://www.github.com/jubaan) // it uses my name and is formatted this way `[@jubaan](https://www.github.com/jubaan)` personal username and no spaces between square brackets and paretheses.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2021-01-13 16:01 UTC, jubaan commented on index.html
> +        </div>
- [ ] TheNYT logo should be a link also

2021-01-13 16:01 UTC, jubaan commented on index.html
> +            <button>Login</button>
- [ ] This should be links also

2021-01-13 16:01 UTC, jubaan commented on index.html
> +                        <p>Manage My Account</p>
- [ ] This elemenst are part of a menu, so they should be links

2021-01-15 08:03 UTC, mcrd25 approved these changes
# Changes Approved :heavy_check_mark: 

Hi Team! :wave: 

You've done enough to warrant a :+1: . Check out my additional comments though! :slightly_smiling_face: 


***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

If you liked my review, consider upskilling me on LinkedIn. And please do connect. [My LinkedIn](https://www.linkedin.com/in/mayadouglas/)


*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2021-01-15 08:03 UTC, mcrd25 commented on index.html
> +                <i class="fa fa-bookmark-o book-mark" aria-hidden="true"></i>
[OPTIONAL]
These should be links

2021-01-15 08:03 UTC, mcrd25 commented on index.html
> +            </aside>
[OPTIONAL]
The sizing for this is slightly bigger than the original

2021-01-29 14:18 UTC, closed without merging